// List of countries with ISO codes, labels, and continent for use in the territory picker
// Source: ISO 3166-1 alpha-2 (general list) with continent groupings
// Continents used: Africa, Asia, Europe, North America, South America, Oceania, Antarctica

export type Continent =
  | 'Africa'
  | 'Asia'
  | 'Europe'
  | 'North America'
  | 'South America'
  | 'Oceania'
  | 'Antarctica';

export interface Country {
  code: string; // ISO 3166-1 alpha-2
  label: string;
  continent: Continent;
}

// Note: Some territories and special regions are included, as many DSPs report/target these separately.
// If you want to hide any, filter them at the UI layer.
const countries: Country[] = [
  // Africa
  { code: 'DZ', label: 'Algeria', continent: 'Africa' },
  { code: 'AO', label: 'Angola', continent: 'Africa' },
  { code: 'BJ', label: 'Benin', continent: 'Africa' },
  { code: 'BW', label: 'Botswana', continent: 'Africa' },
  { code: 'BF', label: 'Burkina Faso', continent: 'Africa' },
  { code: 'BI', label: 'Burundi', continent: 'Africa' },
  { code: 'CM', label: 'Cameroon', continent: 'Africa' },
  { code: 'CV', label: 'Cabo Verde', continent: 'Africa' },
  { code: 'CF', label: 'Central African Republic', continent: 'Africa' },
  { code: 'TD', label: 'Chad', continent: 'Africa' },
  { code: 'KM', label: 'Comoros', continent: 'Africa' },
  { code: 'CD', label: 'Congo (DRC)', continent: 'Africa' },
  { code: 'CG', label: 'Congo (Republic)', continent: 'Africa' },
  { code: 'CI', label: `Côte d'Ivoire`, continent: 'Africa' },
  { code: 'DJ', label: 'Djibouti', continent: 'Africa' },
  { code: 'EG', label: 'Egypt', continent: 'Africa' },
  { code: 'GQ', label: 'Equatorial Guinea', continent: 'Africa' },
  { code: 'ER', label: 'Eritrea', continent: 'Africa' },
  { code: 'SZ', label: 'Eswatini', continent: 'Africa' },
  { code: 'ET', label: 'Ethiopia', continent: 'Africa' },
  { code: 'GA', label: 'Gabon', continent: 'Africa' },
  { code: 'GM', label: 'Gambia', continent: 'Africa' },
  { code: 'GH', label: 'Ghana', continent: 'Africa' },
  { code: 'GN', label: 'Guinea', continent: 'Africa' },
  { code: 'GW', label: 'Guinea-Bissau', continent: 'Africa' },
  { code: 'KE', label: 'Kenya', continent: 'Africa' },
  { code: 'LS', label: 'Lesotho', continent: 'Africa' },
  { code: 'LR', label: 'Liberia', continent: 'Africa' },
  { code: 'LY', label: 'Libya', continent: 'Africa' },
  { code: 'MG', label: 'Madagascar', continent: 'Africa' },
  { code: 'MW', label: 'Malawi', continent: 'Africa' },
  { code: 'ML', label: 'Mali', continent: 'Africa' },
  { code: 'MR', label: 'Mauritania', continent: 'Africa' },
  { code: 'MU', label: 'Mauritius', continent: 'Africa' },
  { code: 'MA', label: 'Morocco', continent: 'Africa' },
  { code: 'MZ', label: 'Mozambique', continent: 'Africa' },
  { code: 'NA', label: 'Namibia', continent: 'Africa' },
  { code: 'NE', label: 'Niger', continent: 'Africa' },
  { code: 'NG', label: 'Nigeria', continent: 'Africa' },
  { code: 'RW', label: 'Rwanda', continent: 'Africa' },
  { code: 'ST', label: 'São Tomé and Príncipe', continent: 'Africa' },
  { code: 'SN', label: 'Senegal', continent: 'Africa' },
  { code: 'SC', label: 'Seychelles', continent: 'Africa' },
  { code: 'SL', label: 'Sierra Leone', continent: 'Africa' },
  { code: 'SO', label: 'Somalia', continent: 'Africa' },
  { code: 'ZA', label: 'South Africa', continent: 'Africa' },
  { code: 'SS', label: 'South Sudan', continent: 'Africa' },
  { code: 'SD', label: 'Sudan', continent: 'Africa' },
  { code: 'TZ', label: 'Tanzania', continent: 'Africa' },
  { code: 'TG', label: 'Togo', continent: 'Africa' },
  { code: 'TN', label: 'Tunisia', continent: 'Africa' },
  { code: 'UG', label: 'Uganda', continent: 'Africa' },
  { code: 'EH', label: 'Western Sahara', continent: 'Africa' },
  { code: 'ZM', label: 'Zambia', continent: 'Africa' },
  { code: 'ZW', label: 'Zimbabwe', continent: 'Africa' },

  // Asia
  { code: 'AF', label: 'Afghanistan', continent: 'Asia' },
  { code: 'AM', label: 'Armenia', continent: 'Asia' },
  { code: 'AZ', label: 'Azerbaijan', continent: 'Asia' },
  { code: 'BH', label: 'Bahrain', continent: 'Asia' },
  { code: 'BD', label: 'Bangladesh', continent: 'Asia' },
  { code: 'BT', label: 'Bhutan', continent: 'Asia' },
  { code: 'BN', label: 'Brunei', continent: 'Asia' },
  { code: 'KH', label: 'Cambodia', continent: 'Asia' },
  { code: 'CN', label: 'China', continent: 'Asia' },
  { code: 'GE', label: 'Georgia', continent: 'Asia' },
  { code: 'HK', label: 'Hong Kong SAR', continent: 'Asia' },
  { code: 'IN', label: 'India', continent: 'Asia' },
  { code: 'ID', label: 'Indonesia', continent: 'Asia' },
  { code: 'IR', label: 'Iran', continent: 'Asia' },
  { code: 'IQ', label: 'Iraq', continent: 'Asia' },
  { code: 'IL', label: 'Israel', continent: 'Asia' },
  { code: 'JP', label: 'Japan', continent: 'Asia' },
  { code: 'JO', label: 'Jordan', continent: 'Asia' },
  { code: 'KZ', label: 'Kazakhstan', continent: 'Asia' },
  { code: 'KW', label: 'Kuwait', continent: 'Asia' },
  { code: 'KG', label: 'Kyrgyzstan', continent: 'Asia' },
  { code: 'LA', label: 'Laos', continent: 'Asia' },
  { code: 'LB', label: 'Lebanon', continent: 'Asia' },
  { code: 'MO', label: 'Macao SAR', continent: 'Asia' },
  { code: 'MY', label: 'Malaysia', continent: 'Asia' },
  { code: 'MV', label: 'Maldives', continent: 'Asia' },
  { code: 'MN', label: 'Mongolia', continent: 'Asia' },
  { code: 'MM', label: 'Myanmar (Burma)', continent: 'Asia' },
  { code: 'NP', label: 'Nepal', continent: 'Asia' },
  { code: 'KP', label: 'North Korea', continent: 'Asia' },
  { code: 'OM', label: 'Oman', continent: 'Asia' },
  { code: 'PK', label: 'Pakistan', continent: 'Asia' },
  { code: 'PS', label: 'Palestinian Territories', continent: 'Asia' },
  { code: 'PH', label: 'Philippines', continent: 'Asia' },
  { code: 'QA', label: 'Qatar', continent: 'Asia' },
  { code: 'SA', label: 'Saudi Arabia', continent: 'Asia' },
  { code: 'SG', label: 'Singapore', continent: 'Asia' },
  { code: 'KR', label: 'South Korea', continent: 'Asia' },
  { code: 'LK', label: 'Sri Lanka', continent: 'Asia' },
  { code: 'SY', label: 'Syria', continent: 'Asia' },
  { code: 'TW', label: 'Taiwan', continent: 'Asia' },
  { code: 'TJ', label: 'Tajikistan', continent: 'Asia' },
  { code: 'TH', label: 'Thailand', continent: 'Asia' },
  { code: 'TL', label: 'Timor-Leste', continent: 'Asia' },
  { code: 'TR', label: 'Turkey', continent: 'Asia' },
  { code: 'TM', label: 'Turkmenistan', continent: 'Asia' },
  { code: 'AE', label: 'United Arab Emirates', continent: 'Asia' },
  { code: 'UZ', label: 'Uzbekistan', continent: 'Asia' },
  { code: 'VN', label: 'Vietnam', continent: 'Asia' },
  { code: 'YE', label: 'Yemen', continent: 'Asia' },

  // Europe
  { code: 'AL', label: 'Albania', continent: 'Europe' },
  { code: 'AD', label: 'Andorra', continent: 'Europe' },
  { code: 'AT', label: 'Austria', continent: 'Europe' },
  { code: 'BY', label: 'Belarus', continent: 'Europe' },
  { code: 'BE', label: 'Belgium', continent: 'Europe' },
  { code: 'BA', label: 'Bosnia and Herzegovina', continent: 'Europe' },
  { code: 'BG', label: 'Bulgaria', continent: 'Europe' },
  { code: 'HR', label: 'Croatia', continent: 'Europe' },
  { code: 'CY', label: 'Cyprus', continent: 'Europe' },
  { code: 'CZ', label: 'Czechia', continent: 'Europe' },
  { code: 'DK', label: 'Denmark', continent: 'Europe' },
  { code: 'EE', label: 'Estonia', continent: 'Europe' },
  { code: 'FI', label: 'Finland', continent: 'Europe' },
  { code: 'FR', label: 'France', continent: 'Europe' },
  { code: 'DE', label: 'Germany', continent: 'Europe' },
  { code: 'GR', label: 'Greece', continent: 'Europe' },
  { code: 'HU', label: 'Hungary', continent: 'Europe' },
  { code: 'IS', label: 'Iceland', continent: 'Europe' },
  { code: 'IE', label: 'Ireland', continent: 'Europe' },
  { code: 'IT', label: 'Italy', continent: 'Europe' },
  { code: 'XK', label: 'Kosovo', continent: 'Europe' },
  { code: 'LV', label: 'Latvia', continent: 'Europe' },
  { code: 'LI', label: 'Liechtenstein', continent: 'Europe' },
  { code: 'LT', label: 'Lithuania', continent: 'Europe' },
  { code: 'LU', label: 'Luxembourg', continent: 'Europe' },
  { code: 'MT', label: 'Malta', continent: 'Europe' },
  { code: 'MD', label: 'Moldova', continent: 'Europe' },
  { code: 'MC', label: 'Monaco', continent: 'Europe' },
  { code: 'ME', label: 'Montenegro', continent: 'Europe' },
  { code: 'NL', label: 'Netherlands', continent: 'Europe' },
  { code: 'MK', label: 'North Macedonia', continent: 'Europe' },
  { code: 'NO', label: 'Norway', continent: 'Europe' },
  { code: 'PL', label: 'Poland', continent: 'Europe' },
  { code: 'PT', label: 'Portugal', continent: 'Europe' },
  { code: 'RO', label: 'Romania', continent: 'Europe' },
  { code: 'RU', label: 'Russia', continent: 'Europe' },
  { code: 'SM', label: 'San Marino', continent: 'Europe' },
  { code: 'RS', label: 'Serbia', continent: 'Europe' },
  { code: 'SK', label: 'Slovakia', continent: 'Europe' },
  { code: 'SI', label: 'Slovenia', continent: 'Europe' },
  { code: 'ES', label: 'Spain', continent: 'Europe' },
  { code: 'SE', label: 'Sweden', continent: 'Europe' },
  { code: 'CH', label: 'Switzerland', continent: 'Europe' },
  { code: 'UA', label: 'Ukraine', continent: 'Europe' },
  { code: 'GB', label: 'United Kingdom', continent: 'Europe' },
  { code: 'VA', label: 'Vatican City', continent: 'Europe' },

  // North America
  { code: 'AG', label: 'Antigua and Barbuda', continent: 'North America' },
  { code: 'BS', label: 'Bahamas', continent: 'North America' },
  { code: 'BB', label: 'Barbados', continent: 'North America' },
  { code: 'BZ', label: 'Belize', continent: 'North America' },
  { code: 'CA', label: 'Canada', continent: 'North America' },
  { code: 'CR', label: 'Costa Rica', continent: 'North America' },
  { code: 'CU', label: 'Cuba', continent: 'North America' },
  { code: 'DM', label: 'Dominica', continent: 'North America' },
  { code: 'DO', label: 'Dominican Republic', continent: 'North America' },
  { code: 'SV', label: 'El Salvador', continent: 'North America' },
  { code: 'GD', label: 'Grenada', continent: 'North America' },
  { code: 'GT', label: 'Guatemala', continent: 'North America' },
  { code: 'HT', label: 'Haiti', continent: 'North America' },
  { code: 'HN', label: 'Honduras', continent: 'North America' },
  { code: 'JM', label: 'Jamaica', continent: 'North America' },
  { code: 'MX', label: 'Mexico', continent: 'North America' },
  { code: 'NI', label: 'Nicaragua', continent: 'North America' },
  { code: 'PA', label: 'Panama', continent: 'North America' },
  { code: 'KN', label: 'Saint Kitts and Nevis', continent: 'North America' },
  { code: 'LC', label: 'Saint Lucia', continent: 'North America' },
  { code: 'VC', label: 'Saint Vincent and the Grenadines', continent: 'North America' },
  { code: 'TT', label: 'Trinidad and Tobago', continent: 'North America' },
  { code: 'US', label: 'United States', continent: 'North America' },

  // South America
  { code: 'AR', label: 'Argentina', continent: 'South America' },
  { code: 'BO', label: 'Bolivia', continent: 'South America' },
  { code: 'BR', label: 'Brazil', continent: 'South America' },
  { code: 'CL', label: 'Chile', continent: 'South America' },
  { code: 'CO', label: 'Colombia', continent: 'South America' },
  { code: 'EC', label: 'Ecuador', continent: 'South America' },
  { code: 'GY', label: 'Guyana', continent: 'South America' },
  { code: 'PY', label: 'Paraguay', continent: 'South America' },
  { code: 'PE', label: 'Peru', continent: 'South America' },
  { code: 'SR', label: 'Suriname', continent: 'South America' },
  { code: 'UY', label: 'Uruguay', continent: 'South America' },
  { code: 'VE', label: 'Venezuela', continent: 'South America' },

  // Oceania
  { code: 'AU', label: 'Australia', continent: 'Oceania' },
  { code: 'FJ', label: 'Fiji', continent: 'Oceania' },
  { code: 'KI', label: 'Kiribati', continent: 'Oceania' },
  { code: 'MH', label: 'Marshall Islands', continent: 'Oceania' },
  { code: 'FM', label: 'Micronesia', continent: 'Oceania' },
  { code: 'NR', label: 'Nauru', continent: 'Oceania' },
  { code: 'NZ', label: 'New Zealand', continent: 'Oceania' },
  { code: 'PW', label: 'Palau', continent: 'Oceania' },
  { code: 'PG', label: 'Papua New Guinea', continent: 'Oceania' },
  { code: 'WS', label: 'Samoa', continent: 'Oceania' },
  { code: 'SB', label: 'Solomon Islands', continent: 'Oceania' },
  { code: 'TO', label: 'Tonga', continent: 'Oceania' },
  { code: 'TV', label: 'Tuvalu', continent: 'Oceania' },
  { code: 'VU', label: 'Vanuatu', continent: 'Oceania' },

  // Antarctica (research territories and territories without permanent residents)
  { code: 'AQ', label: 'Antarctica', continent: 'Antarctica' },

  // Special territories commonly surfaced by DSPs (Americas/Europe misc.)
  { code: 'AI', label: 'Anguilla', continent: 'North America' },
  { code: 'AW', label: 'Aruba', continent: 'North America' },
  { code: 'BM', label: 'Bermuda', continent: 'North America' },
  { code: 'BQ', label: 'Caribbean Netherlands', continent: 'North America' },
  { code: 'KY', label: 'Cayman Islands', continent: 'North America' },
  { code: 'GL', label: 'Greenland', continent: 'North America' },
  { code: 'GP', label: 'Guadeloupe', continent: 'North America' },
  { code: 'MQ', label: 'Martinique', continent: 'North America' },
  { code: 'MS', label: 'Montserrat', continent: 'North America' },
  { code: 'PR', label: 'Puerto Rico', continent: 'North America' },
  { code: 'BL', label: 'Saint Barthélemy', continent: 'North America' },
  { code: 'MF', label: 'Saint Martin', continent: 'North America' },
  { code: 'PM', label: 'Saint Pierre and Miquelon', continent: 'North America' },
  { code: 'TC', label: 'Turks and Caicos Islands', continent: 'North America' },
  { code: 'VG', label: 'Virgin Islands (British)', continent: 'North America' },
  { code: 'VI', label: 'Virgin Islands (U.S.)', continent: 'North America' },

  // European territories
  { code: 'AX', label: 'Åland Islands', continent: 'Europe' },
  { code: 'GG', label: 'Guernsey', continent: 'Europe' },
  { code: 'IM', label: 'Isle of Man', continent: 'Europe' },
  { code: 'JE', label: 'Jersey', continent: 'Europe' },
  { code: 'GI', label: 'Gibraltar', continent: 'Europe' },

  // Additional UN members and recognized territories missing above
  { code: 'AS', label: 'American Samoa', continent: 'Oceania' },
  { code: 'PF', label: 'French Polynesia', continent: 'Oceania' },
  { code: 'GU', label: 'Guam', continent: 'Oceania' },
  { code: 'NC', label: 'New Caledonia', continent: 'Oceania' },
  { code: 'MP', label: 'Northern Mariana Islands', continent: 'Oceania' },
  { code: 'RE', label: 'Réunion', continent: 'Africa' },
  { code: 'YT', label: 'Mayotte', continent: 'Africa' },
  { code: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha', continent: 'Africa' },
  { code: 'WF', label: 'Wallis and Futuna', continent: 'Oceania' },
  { code: 'FO', label: 'Faroe Islands', continent: 'Europe' },
  { code: 'SJ', label: 'Svalbard and Jan Mayen', continent: 'Europe' },
];

// Helper: countries grouped by continent for quick-select actions
export const continents: { key: Continent; name: Continent; countryCodes: string[] }[] = [
  {
    key: 'Africa',
    name: 'Africa',
    countryCodes: countries.filter(c => c.continent === 'Africa').map(c => c.code),
  },
  {
    key: 'Asia',
    name: 'Asia',
    countryCodes: countries.filter(c => c.continent === 'Asia').map(c => c.code),
  },
  {
    key: 'Europe',
    name: 'Europe',
    countryCodes: countries.filter(c => c.continent === 'Europe').map(c => c.code),
  },
  {
    key: 'North America',
    name: 'North America',
    countryCodes: countries.filter(c => c.continent === 'North America').map(c => c.code),
  },
  {
    key: 'South America',
    name: 'South America',
    countryCodes: countries.filter(c => c.continent === 'South America').map(c => c.code),
  },
  {
    key: 'Oceania',
    name: 'Oceania',
    countryCodes: countries.filter(c => c.continent === 'Oceania').map(c => c.code),
  },
  {
    key: 'Antarctica',
    name: 'Antarctica',
    countryCodes: countries.filter(c => c.continent === 'Antarctica').map(c => c.code),
  },
];

export default countries;
